# Practical 10

**Aim:** Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensional arrays.

### 1. Array Creation

In [1]:
import numpy as np

arr_1d = np.array([100, 200, 300, 400])
arr_2d = np.array([[1, 3, 5], [7, 9, 11]])

print("1D:", arr_1d)
print("2D:\n", arr_2d)

print("Zeros (2x3):\n", np.zeros((2, 3)))
print("Ones (3x2):\n", np.ones((3, 2)))
print("Sequence (0 to 20 by 4):", np.arange(0, 24, 4))
print("Linear Space (1 to 5, 5 values):", np.linspace(1, 5, 5))
print("Eye (4x4):\n", np.eye(4))

1D: [100 200 300 400]
2D:
 [[ 1  3  5]
 [ 7  9 11]]
Zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Sequence (0 to 20 by 4): [ 0  4  8 12 16 20]
Linear Space (1 to 5, 5 values): [1. 2. 3. 4. 5.]
Eye (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 2. Indexing and Slicing

In [2]:
vals = np.array([12, 24, 36, 48, 60, 72])
print("First & Last:", vals[0], vals[-1])
print("Slice 1 to 4:", vals[1:4])

table = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print("\nTable:\n", table)
print("Row 0, Col 3:", table[0, 3])
print("Middle rows & cols:\n", table[1:3, 1:3])
print("Row 1 complete:", table[1, :])

First & Last: 12 72
Slice 1 to 4: [24 36 48]

Table:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Row 0, Col 3: 40
Middle rows & cols:
 [[ 60  70]
 [100 110]]
Row 1 complete: [50 60 70 80]


### 3. Reshaping

In [3]:
nums = np.arange(10, 22)
print("Original vector:", nums)

reshaped_mat = nums.reshape(3, 4)
print("Reshaped 3x4:\n", reshaped_mat)

print("Ravel (1D):", reshaped_mat.ravel())

Original vector: [10 11 12 13 14 15 16 17 18 19 20 21]
Reshaped 3x4:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Ravel (1D): [10 11 12 13 14 15 16 17 18 19 20 21]


### 4. Broadcasting

In [4]:
arr_A = np.array([[2, 4], [6, 8], [10, 12]])
arr_B = np.array([10, 20])

print("Array A:\n", arr_A)
print("Array B:", arr_B)
print("Broadcasting Addition:\n", arr_A + arr_B)
print("Broadcasting Division:\n", arr_A / 2)

Array A:
 [[ 2  4]
 [ 6  8]
 [10 12]]
Array B: [10 20]
Broadcasting Addition:
 [[12 24]
 [16 28]
 [20 32]]
Broadcasting Division:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


### 5. Matrix Operations

In [5]:
A = np.array([[1, 4], [2, 3]])
B = np.array([[5, 1], [0, 2]])

print("A + B:\n", A + B)
print("A * B (element-wise):\n", A * B)
print("Matrix Multiplication (@):\n", A @ B)

print("Cumulative Sum:", A.cumsum())
print("Column Mean:", A.mean(axis=0))
print("Variance:", round(A.var(), 2))

A + B:
 [[6 5]
 [2 5]]
A * B (element-wise):
 [[5 4]
 [0 6]]
Matrix Multiplication (@):
 [[ 5  9]
 [10  8]]
Cumulative Sum: [ 1  5  7 10]
Column Mean: [1.5 3.5]
Variance: 1.25
